# Generated by Django 3.2.10 on 2021-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('todo_status', models.BooleanField(default=False, verbose_name='Completed')),
            ],
            options={
                'ordering': ['todo_status'],
            },
        ),
    ]
